# Use the official SQL Server image
FROM mcr.microsoft.com/mssql/server

# Set the SA password
ENV SA_PASSWORD YourSaPassword

# Accept the EULA
ENV ACCEPT_EULA=Y

# Create a new database
ENV MSSQL_DB YourDatabaseName

# Expose the port for SQL Server
EXPOSE 1433
