version: '3.8'

services:
  sql-server:
    build:
      context: ./Database/Dockerfile
    ports:
      - "1433:1433"

  dotnet-core:
    build:
      context: ./API/Dockerfile
    ports:
      - "5000:5000"  # Adjust the port based on your ASP.NET Core app configuration
    depends_on:
      - sql-server

  react-app:
    build:
      context: ./Frontend/Dockerfile
    ports:
      - "3000:3000"  # Adjust the port based on your React.js app configuration
