version: '3.8'

services:
  aspnet-app:
    image: your-aspnet-app
    ports:
      - "80:80"
    depends_on:
      - mssql-server

  mssql-server:
    image: your-mssql-server
    ports:
      - "1433:1433"

  react-app:
    image: your-react-app
    ports:
      - "3000:3000"
    depends_on:
      - aspnet-app
